### ISSUE TITLE
Some matrix todo list

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#184]
- [x] Replace `windows` with `view` for `nmod_mat` and `fmpz_mat`.
- [ ] Write a `view` function for all other matrix types.
- [x] Scatter `@inbounds` across the matrix code (but first understand how it works).
- [ ] Save the `GenMat` in julia friendly order (almost done).
- [ ] Make `A[1:n, 1:m]` work for Nemo matrices.
- [ ] Disentangle `GenMat` and `MatElem`.
- [ ] Make matrices more collection like (allow `A[i]` to iterate through the rows).

Feel free to add more.
