### ISSUE TITLE
Another todo list

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#7]
I just want to record some questions and tasks which emerged in the discussion of #4. Feel free to edit this.

Functionality which needs to be rolled out:
- [x] Matrix constructors with 1-dimensional arrays for all matrix types (see `fmpz_mat`)
- [x] zero!, one! for non-immutable types (see `nmod_poly` or `fmpz_mat`)
- [x] Valuation for polynomials (over fields) (see `nmod_poly`)
- [x] swap_rows and swap_rows! for generic matrices (see `arb_mat`)

Things we need to find conventions for and apply them consequently:
- [x] `is_hnf` versus `isprime`
- [x] Underscores in function names
- [x] How to handle names of "internal" functions, i.e., how to hide them
- [ ] Consistent error messages (using error objects?)

Renaming:
 - [ ] `isnegative` to `has_minus_sign` (or something like that).

Things which would be nice to have or improve:
- [ ] Valuation of polynomials with logarithmic complexity.
